### ISSUE TITLE
Failed to open file '/bitnami/mariadb/data//galera.cache': 1 (Operation not permitted)

### ISSUE THREAD

**Issue by jacekkotynski** [bitnami/bitnami-docker-mariadb-galera#11]
This issue might be related to: #1 

**Description**
While working on a single docker swarm with docker compose set-up as below. When referencing a volume as local directory (this does not happen if the volume is virtual / not referenced) I'm getting a following error set:
`p9div 2020-02-25 11:23:31 0 [Note] WSREP: Found saved state: 00000000-0000-0000-0000-000000000000:-1, safe_to_bootstrap: 1`
`p9div 2020-02-25 11:23:31 0 [ERROR] WSREP: Failed to open file '/bitnami/mariadb/data//galera.cache': 1 (Operation not permitted)`
`p9div 	 at galerautils/src/gu_fdesc.cpp:constructor_common():141`
`p9div 2020-02-25 11:23:31 0 [ERROR] WSREP: Failed to create a new provider '/opt/bitnami/mariadb/lib/libgalera_smm.so' with options '':Failed to initialize wsrep provider`
`p9div 2020-02-25 11:23:31 0 [ERROR] WSREP: Failed to load provider`
`p9div 2020-02-25 11:23:31 0 [ERROR] Aborting`

This results in the host failover - and instance restarts

**Steps to reproduce the issue:**

1. Initialize local docker swarm (single instance)
2. RUN: `docker stack up -c .\docker-compose.yml yourappname`

docker-compose.yml:
```
version: '3.7'

services:
    mariadb-galera:
        image: 'bitnami/mariadb-galera:10.4.12'
        ports:
            - 3306:3306
            - 4444:4444
            - 4567:4567
            - 4568:4568
        volumes:
            - ./data/galera0/mariadb:/bitnami/mariadb
        environment:
            - MARIADB_ROOT_PASSWORD=SomeRandomPassword
            - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=100
            - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
            - MARIADB_GALERA_CLUSTER_NAME=GaleraFleet
            - MARIADB_GALERA_MARIABACKUP_USER=backupuser
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=AnotherRandomPassword
        networks:
            - galera-network
        depends_on:
            - swarmmanager
    slave-1:
        image: 'bitnami/mariadb-galera:10.4.12'
        ports:
            - 3307:3306
            - 4444
            - 4567
            - 4568
        volumes:
            - ./data/galera1/mariadb:/bitnami/mariadb
        environment:
            - MARIADB_ROOT_PASSWORD=SomeRandomPassword
            - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera
            - MARIADB_GALERA_CLUSTER_NAME=GaleraFleet
            - MARIADB_GALERA_MARIABACKUP_USER=backupuser
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=AnotherRandomPassword
        networks:
            - galera-network
        depends_on:
            - mariadb-galera
    slave-2:
        image: 'bitnami/mariadb-galera:10.4.12'
        ports:
            - 3308:3306
            - 4444
            - 4567
            - 4568
        volumes:
            - ./data/galera2/mariadb:/bitnami/mariadb
        environment:
            - MARIADB_ROOT_PASSWORD=SomeRandomPassword
            - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera
            - MARIADB_GALERA_CLUSTER_NAME=GaleraFleet
            - MARIADB_GALERA_MARIABACKUP_USER=backupuser
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=AnotherRandomPassword
        networks:
            - galera-network
        depends_on:
            - slave-1
    swarmmanager:
        image: swarmpit/swarmpit:latest
        environment:
            SWARMPIT_DB: http://swarmmanagerdb:5984
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        ports:
            - 9000:8080
        networks:
            - galera-network
        deploy:
            placement:
                constraints:
                    - node.role == manager
        depends_on:
            - swarmmanagerdb
    swarmmanagerdb:
        image: apache/couchdb:latest
        volumes:
            - swarmmanagerdb-data:/opt/couchdb/data
        networks:
            - galera-network
networks:
    galera-network:
        driver: overlay
volumes:
    swarmmanagerdb-data:
        driver: local
```

**Describe the results you received:**
With the file like above we get the crush "failed to open galera.cache"
Running same docker-compose.yml without the Volumes for galera data will result in proper startup

**Describe the results you expected:**
Expected result would be to run the image with data presistency

**Version**

- Output of `docker version`:

```
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Server:
 Containers: 13
  Running: 4
  Paused: 0
  Stopped: 9
 Images: 3
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 0atmf6pib75fc0v36f1inxhlo
  Is Manager: true
  ClusterID: ewrut6wuw1hzhumhfdyoku7y5
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.65.3
  Manager Addresses:
   192.168.65.3:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 14
 Total Memory: 31.35GiB
 Name: docker-desktop
 ID: JL2F:J4N3:B66N:6QFB:U2HD:6XYD:UVJD:I6GS:M6AO:MOS4:EB6O:IDIG
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 98
  Goroutines: 20950
  System Time: 2020-02-25T11:59:43.256614601Z
  EventsListeners: 8
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker Desktop for Windows running swarm and compose on linux containers

**Comment by juan131** [comment]
Hi @jacekkotynski 

I noticed you're mounting the same volume in every MariaDB Galera replica. I highly discouraged you to do so. Instead, use a different data volume per replica.

---

If after using a volume per replica the issue persists, it's highly likely to be a permissions issue in the volumes you're attaching to your MariaDB Galera containers.

I'm not an expert on Docker Swarm, and I think there's no way to specify the ownership/permissions on the volumes you want to attach. Therefore, it's very likely you'll have to use another container that mounts the same volume you're attaching to Galera replicas and adapt the permissions.

MariaDB Galera service is running with user `msyql` by default, See:

```console
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
mysql        1  0.2  5.3 1883232 108448 ?      Ssl  08:06   0:00 /opt/bitnami/mariadb/sbin/mysqld ...
```

Therefore, you need to ensure the directory `/bitnami/mariadb/data` belongs to that user and it has writing permissions.

> Note: I saw you're naming your MariaDB Galera replicas `mariadb-galera`, `slave-1`, `slave-2`. Please note that MariaDB Galera is a multi-master database, there are no slaves on this setup.

**Comment by jacekkotynski** [comment]
Hi @juan131 

Regarding the volumes there are 3 separate volumes (you probably missed it)
 ./data/`galera1`/mariadb:/bitnami/mariadb
 ./data/`galera2`/mariadb:/bitnami/mariadb
 ./data/`galera3`/mariadb:/bitnami/mariadb
In case you mean physical volume that shouldn't be the problem other than I/O

Regarding the access rights:
1. When I turn off Galera and run just MariaDB single instance or multiple separate instances there are no issues (Swarm)
2. When I turn on Galera and run instances there is immediate problem with galera.cache (also the path with // is very strange -> )

Per your note :) Point taken. 
The naming convention is like that for a time being cause I use "Master" for bootstrapping while other two are always connecting - unless this makes any difference?

**Comment by juan131** [comment]
Hi @jacekkotynski 

The naming convention is just for you to not get confused, but as you said it makes no difference.

> Regarding the volumes there are 3 separate volumes (you probably missed it)
> - ./data/galera1/mariadb:/bitnami/mariadb (container 1)
> - ./data/galera2/mariadb:/bitnami/mariadb (container 2)
> - ./data/galera3/mariadb:/bitnami/mariadb (container 3)
> In case you mean physical volume that shouldn't be the problem other than I/O

I didn't notice you're using different subpaths in your mount points. In theory, it should work as it's. 

Could you run the command below on the container that are complaining about `galera.cache` file?

```
$ ls -la /bitnami/mariadb/data/
```

By the way, the environment variable below should be set on every repilca (it's only set in the `mariadb-galera` one):

```yaml
            - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=100
```

**Comment by jacekkotynski** [comment]
I've run the command in composer mode (guess there is no difference to credentials on the container) - as in SWARM mode there is no way to connect to it - it will shut down an restart without giving you a chance to do that (due to the fact that galera.cache access is critical error)
```
# ls -l /bitnami/mariadb/data
total 0
-rwxr-xr-x 1 root root    24576 Feb 26 09:19 aria_log.00000001
-rwxr-xr-x 1 root root       52 Feb 26 09:19 aria_log_control
-rwxr-xr-x 1 root root        0 Feb 26 09:19 galera.cache
-rwxr-xr-x 1 root root        0 Feb 26 09:19 grastate.dat
-rwxr-xr-x 1 root root      972 Feb 26 09:19 ib_buffer_pool
-rwxr-xr-x 1 root root 50331648 Feb 26 09:19 ib_logfile0
-rwxr-xr-x 1 root root 50331648 Feb 26 09:19 ib_logfile1
-rwxr-xr-x 1 root root 12582912 Feb 26 09:19 ibdata1
drwxrwxrwx 1 root root    16384 Feb 26 09:19 mysql
-rwxr-xr-x 1 root root    26332 Feb 26 09:19 mysql-bin.000001
-rwxr-xr-x 1 root root       19 Feb 26 09:19 mysql-bin.index
-rwxr-xr-x 1 root root        7 Feb 26 09:19 mysql-bin.state
drwxrwxrwx 1 root root        0 Feb 26 09:19 performance_schema
drwxrwxrwx 1 root root        0 Feb 26 09:19 test
#
```

And also set the MARIADB_EXTRA_FLAGS for all containers

**Comment by juan131** [comment]
Hi @jacekkotynski 

Theres' something odd there. This is a normal output:

```console
$ docker-compose exec mariadb-galera ls -la /bitnami/mariadb/data
total 254052
drwxrwxr-x 5 mysql mysql      4096 Feb 27 07:17 .
drwxrwxr-x 3 root  root       4096 Feb 27 07:16 ..
-rw-rw---- 1 mysql mysql     16384 Feb 27 07:17 aria_log.00000001
-rw-rw---- 1 mysql mysql        52 Feb 27 07:17 aria_log_control
-rw-rw---- 1 mysql mysql 134219048 Feb 27 07:17 galera.cache
-rw-rw---- 1 mysql mysql       113 Feb 27 07:17 grastate.dat
-rw-rw---- 1 mysql mysql       170 Feb 27 07:17 gvwstate.dat
-rw-rw---- 1 mysql mysql       976 Feb 27 07:17 ib_buffer_pool
-rw-rw---- 1 mysql mysql  50331648 Feb 27 07:17 ib_logfile0
-rw-rw---- 1 mysql mysql  50331648 Feb 27 07:16 ib_logfile1
-rw-rw---- 1 mysql mysql  12582912 Feb 27 07:17 ibdata1
-rw-rw---- 1 mysql mysql  12582912 Feb 27 07:17 ibtmp1
-rw-rw---- 1 mysql mysql         0 Feb 27 07:17 multi-master.info
drwx------ 2 mysql mysql      4096 Feb 27 07:16 mysql
-rw-rw---- 1 mysql mysql     26679 Feb 27 07:16 mysql-bin.000001
-rw-rw---- 1 mysql mysql      2833 Feb 27 07:17 mysql-bin.000002
-rw-rw---- 1 mysql mysql       342 Feb 27 07:17 mysql-bin.000003
-rw-rw---- 1 mysql mysql        57 Feb 27 07:17 mysql-bin.index
drwx------ 2 mysql mysql      4096 Feb 27 07:16 performance_schema
drwx------ 2 mysql mysql      4096 Feb 27 07:16 test
```

As you can see the files belong to the user "mysql" (the one running MariaDB Galera service).

Do you know if there's any limitation to change the ownership of the files in the type of volumes you're using? They should have been adapted by the initialization logic of the container.

**Comment by jacekkotynski** [comment]
Hi @juan131 

I don't know what is the logic running behind bitnamis container here so I can't tell what user should have right. 

However your post gave me an idea that I just tested. Let's consider just the part of docker-compose.yml that's running just the mariadb and do a quick test (why is it different with volume mounted and not)
I've setup bootstrap node to mount to local volume.
I've setup second master (slave1) to mount local volume
I've setup third master to (slave2) to not mount local volume

and surprisingly there is a difference 
when the volume is mapping windows directory it's all set to:
```
# ls -la /bitnami/mariadb/data
total 0
drwxrwxrwx 1 root root     4096 Feb 27 07:46 .
drwxrwxrwx 1 root root        0 Feb 27 07:46 ..
-rwxr-xr-x 1 root root    24576 Feb 27 07:46 aria_log.00000001
-rwxr-xr-x 1 root root       52 Feb 27 07:46 aria_log_control
-rwxr-xr-x 1 root root        0 Feb 27 07:46 galera.cache
-rwxr-xr-x 1 root root        0 Feb 27 07:46 grastate.dat
-rwxr-xr-x 1 root root      972 Feb 27 07:46 ib_buffer_pool
-rwxr-xr-x 1 root root 50331648 Feb 27 07:46 ib_logfile0
-rwxr-xr-x 1 root root 50331648 Feb 27 07:46 ib_logfile1
-rwxr-xr-x 1 root root 12582912 Feb 27 07:46 ibdata1
drwxrwxrwx 1 root root    16384 Feb 27 07:46 mysql
-rwxr-xr-x 1 root root    26332 Feb 27 07:46 mysql-bin.000001
-rwxr-xr-x 1 root root       19 Feb 27 07:46 mysql-bin.index
-rwxr-xr-x 1 root root        7 Feb 27 07:46 mysql-bin.state
drwxrwxrwx 1 root root        0 Feb 27 07:46 performance_schema
drwxrwxrwx 1 root root        0 Feb 27 07:46 test
```
wehn it's running virtual non persistent volume:
```
drwxrwxr-x 1 mysql mysql      4096 Feb 27 07:39 .
drwxrwxr-x 1 root  root       4096 Feb 26 17:46 ..
-rw-rw---- 1 mysql mysql     24576 Feb 27 07:37 aria_log.00000001
-rw-rw---- 1 mysql mysql        52 Feb 27 07:37 aria_log_control
-rw-rw---- 1 mysql mysql 134219032 Feb 27 07:39 galera.cache
-rw-rw---- 1 mysql mysql       113 Feb 27 07:39 grastate.dat
-rw-rw---- 1 mysql mysql       170 Feb 27 07:39 gvwstate.dat
-rw-rw---- 1 mysql mysql      1048 Feb 27 07:37 ib_buffer_pool
-rw-rw---- 1 mysql mysql  50331648 Feb 27 07:40 ib_logfile0
-rw-rw---- 1 mysql mysql  50331648 Feb 27 07:34 ib_logfile1
-rw-rw---- 1 mysql mysql  12582912 Feb 27 07:40 ibdata1
-rw-rw---- 1 mysql mysql  12582912 Feb 27 07:39 ibtmp1
-rw-rw---- 1 mysql mysql         0 Feb 27 07:34 multi-master.info
drwx------ 2 mysql mysql      4096 Feb 27 07:34 mysql
-rw-rw---- 1 mysql mysql     26332 Feb 27 07:34 mysql-bin.000001
-rw-rw---- 1 mysql mysql      2509 Feb 27 07:34 mysql-bin.000002
-rw-rw---- 1 mysql mysql       365 Feb 27 07:37 mysql-bin.000003
-rw-rw---- 1 mysql mysql       342 Feb 27 07:39 mysql-bin.000004
-rw-rw---- 1 mysql mysql        76 Feb 27 07:39 mysql-bin.index
drwx------ 2 mysql mysql      4096 Feb 27 07:34 performance_schema
drwx------ 2 mysql mysql      4096 Feb 27 07:34 test
```

So I decided to make a test and the result is even more surprising (I don't know if this is an OS issue or container issue at this point)

```
# ls -la /bitnami/mariadb/data
total 0
drwxrwxrwx 1 root root     4096 Feb 27 07:46 .
drwxrwxrwx 1 root root        0 Feb 27 07:46 ..
-rwxr-xr-x 1 root root    24576 Feb 27 07:46 aria_log.00000001
-rwxr-xr-x 1 root root       52 Feb 27 07:46 aria_log_control
-rwxr-xr-x 1 root root        0 Feb 27 07:46 galera.cache
-rwxr-xr-x 1 root root        0 Feb 27 07:46 grastate.dat
-rwxr-xr-x 1 root root      972 Feb 27 07:46 ib_buffer_pool
-rwxr-xr-x 1 root root 50331648 Feb 27 07:46 ib_logfile0
-rwxr-xr-x 1 root root 50331648 Feb 27 07:46 ib_logfile1
-rwxr-xr-x 1 root root 12582912 Feb 27 07:46 ibdata1
drwxrwxrwx 1 root root    16384 Feb 27 07:46 mysql
-rwxr-xr-x 1 root root    26332 Feb 27 07:46 mysql-bin.000001
-rwxr-xr-x 1 root root       19 Feb 27 07:46 mysql-bin.index
-rwxr-xr-x 1 root root        7 Feb 27 07:46 mysql-bin.state
drwxrwxrwx 1 root root        0 Feb 27 07:46 performance_schema
drwxrwxrwx 1 root root        0 Feb 27 07:46 test
# chown -R mysql:mysql /bitnami/mariadb/data
# ls -la /bitnami/mariadb/data
total 0
drwxrwxrwx 1 root root     4096 Feb 27 07:46 .
drwxrwxrwx 1 root root        0 Feb 27 07:46 ..
-rwxr-xr-x 1 root root    24576 Feb 27 07:46 aria_log.00000001
-rwxr-xr-x 1 root root       52 Feb 27 07:46 aria_log_control
-rwxr-xr-x 1 root root        0 Feb 27 07:46 galera.cache
-rwxr-xr-x 1 root root        0 Feb 27 07:46 grastate.dat
-rwxr-xr-x 1 root root      972 Feb 27 07:46 ib_buffer_pool
-rwxr-xr-x 1 root root 50331648 Feb 27 07:46 ib_logfile0
-rwxr-xr-x 1 root root 50331648 Feb 27 07:46 ib_logfile1
-rwxr-xr-x 1 root root 12582912 Feb 27 07:46 ibdata1
drwxrwxrwx 1 root root    16384 Feb 27 07:46 mysql
-rwxr-xr-x 1 root root    26332 Feb 27 07:46 mysql-bin.000001
-rwxr-xr-x 1 root root       19 Feb 27 07:46 mysql-bin.index
-rwxr-xr-x 1 root root        7 Feb 27 07:46 mysql-bin.state
drwxrwxrwx 1 root root        0 Feb 27 07:46 performance_schema
drwxrwxrwx 1 root root        0 Feb 27 07:46 test
```










config just for reference
```
    mariadb-galera:
        #https://github.com/bitnami/bitnami-docker-mariadb-galera
        image: 'bitnami/mariadb-galera:10.4.12'
        ports:
            - 3306:3306
            - 4444:4444
            - 4567:4567
            - 4568:4568
        volumes:
            - ./data/galera0/mariadb:/bitnami/mariadb
        environment:
            #NOT RECOMMENDED FOR PROD :)
            #- ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_ROOT_PASSWORD=SomeRandomPassword
            - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=100
            - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
            - MARIADB_GALERA_CLUSTER_NAME=GaleraFleet
            - MARIADB_GALERA_MARIABACKUP_USER=backupuser
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=AnotherRandomPassword
        networks:
            - website-network
            #- galera-network
        labels:
            - "traefik.enable=true"
            - "traefik.tcp.services.mariadb.loadbalancer.server.port=3306"
            - "traefik.tcp.routers.mariadb.service=mariadb"
            - "traefik.tcp.routers.mariadb.entrypoints=sql"
            - "traefik.docker.network=website-network"
            
            
   
    slave-1:
        image: 'bitnami/mariadb-galera:10.4.12'
        ports:
            - 3307:3306
            - 4444
            - 4567
            - 4568
        volumes:
            - ./data/galera1/mariadb:/bitnami/mariadb
        environment:
            - MARIADB_ROOT_PASSWORD=SomeRandomPassword
            - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=100
            - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera
            - MARIADB_GALERA_CLUSTER_NAME=GaleraFleet
            - MARIADB_GALERA_MARIABACKUP_USER=backupuser
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=AnotherRandomPassword
        networks:
            - galera-network
        depends_on:
            - mariadb-galera
    
    slave-2:
        image: 'bitnami/mariadb-galera:10.4.12'
        ports:
            - 3308:3306
            - 4444
            - 4567
            - 4568
        #volumes:
        #    - ./data/galera2/mariadb:/bitnami/mariadb
        environment:
            - MARIADB_ROOT_PASSWORD=SomeRandomPassword
            - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=100
            - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera
            - MARIADB_GALERA_CLUSTER_NAME=GaleraFleet
            - MARIADB_GALERA_MARIABACKUP_USER=backupusert
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=AnotherRandomPassword
        networks:
            - galera-network
        depends_on:
            - slave-1
```

**Comment by juan131** [comment]
Hi @jacekkotynski 

> when the volume is mapping windows directory it's all set to...

We've seen errors like this in the past when mounting Windows volumes that are not 100% compatible with the file permissions/ownership system used on Linux/Unix.

Could you try using "docker volumes" instead of directly  a host path?

```yaml
services:
  mariadb-galera:
    (...)
    volumes:
      - 'mariadb_galera_data:/bitnami/mariadb'
(...)
volumes:
  mariadb_galera_data:
    driver: local
```
