### ISSUE TITLE
Docker Swarm Deploy example - multi master

### ISSUE THREAD

**Issue by csib** [bitnami/bitnami-docker-mariadb-galera#13]
Hi,

Please extend/add docker-compose.yml file for a multi-master replication cluster in Swarm. I've done it on my own, but I am not an expert like you, and my log is full with:

> 2020-03-25 16:59:36 0 [Note] WSREP: (07f45356, 'tcp://0.0.0.0:4567') reconnecting to ef87323b (tcp://10.0.1.21:4567), attempt 121950

I think this is not a healthy behaviour, but everything seems functional.

Thank you!

**Comment by juan131** [comment]
Hi @csib 

Thanks so much for your suggestion.

At this very moment, our pipeline tests the containers locally (using "docker-compose") and on different K8s distributions (using the associated Helm chart). However, **we do not test our containers using Docker Swarm.**

We want to ensure that whatever we provide through this repo is tested on a daily basis. Therefore, we cannot provide a "docker-compose.yaml" for Swarm since we don't have the tools in place to test it properly, and we cannot guarantee is working as expected.

**Comment by Ornias1993** [comment]
@csib To add a bit: It isn't that hard, but you might need a bit of compose-fu.
You need to check how you handle hostnames. If you like you can post your compose.yml here and have people take a look. if everything is alright

However I also understand @juan131 very well:
The moment you supply example config (even when you add a big NOT-SUPPORTED on top), people expect it to be supported.

**Comment by Ornias1993** [comment]
@csib Lets be helpfull.. I set one up for you:

```
version: '3'
services:
  galera0:
      image: bitnami/mariadb-galera:latest
      hostname: galera0
      networks:
        - internal
      environment:
        - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
        - MARIADB_ROOT_PASSWORD=PASSWORD
        - MARIADB_GALERA_MARIABACKUP_PASSWORD=PASSWORD

      volumes:
        - /var/data/mariadb/galera0/db:/bitnami/mariadb
        - /var/data/mariadb/galera0/config:/opt/bitnami/mariadb/conf/

  galera:
      image: bitnami/mariadb-galera:latest
      hostname: galera{{.Task.Slot}}
      networks:
        - internal
      environment:
         - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://galera0
         - MARIADB_ROOT_PASSWORD=PASSWORD
         - MARIADB_GALERA_MARIABACKUP_PASSWORD=PASSWORD
      volumes:
        - /var/data/mariadb/galera{{.Task.Slot}}/db:/bitnami/mariadb
        - /var/data/mariadb/galera{{.Task.Slot}}/config:/opt/bitnami/mariadb/conf/



#  maxscale:
#      image: 'mariadb/maxscale:latest'
#      networks:
#          - internal
#      depends_on:
#          - master
#          - slave
#      volumes:
#          - /var/data/mariadb/maxscale:/etc/maxscale.cnf.d
#      ports:
#          - "4006:4006"
#          - "4008:4008"
#          - "8989:8989"
networks:
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.70.0/24

```

Note: Also added example maxscale config, commented out (because it isn't plug and play).
One thing I'm not happy about and didn't fully figure out is how to make sure the permissions are right. Installing required manual intervention a few times running `chown -R 1001:1001 /var/data/mariadb` in the background

**Comment by juan131** [comment]
Hi @Ornias1993 

Thanks so much for sharing this solution for Docker Swarm!! We really appreciate your collaboration.

 > The moment you supply example config (even when you add a big NOT-SUPPORTED on top), people expect it to be supported.

+100 
That's something we want to avoid, even though we'll reach a wider set of users providing them. However, if we don't have a way to automatically test it on a daily basis, then we prefer not to publish it.

**Comment by Ornias1993** [comment]
> Thanks so much for sharing this solution for Docker Swarm!! We really appreciate your collaboration.

The permission issues and such do prove your point though: it is not just a copy-and-paste and does need some custom TLC. Afaik the issue is the difference in how resp. Docker Swarm and k8s, handle container permissions. But someone with more experience in docker permissions should take a look at that.

> +100
> That's something we want to avoid, even though we'll reach a wider set of users providing them. However, if we don't have a way to automatically test it on a daily basis, then we prefer not to publish it.

I might take a look at it someday, afaik mariadb has their own test code public using docker swarm.


Another thing I want to point out:
`- MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes` requires an actual "yes", it would be nice if we can also accept "1". 
`- MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://galera0` when used on a bootstrap node goes haywire (as expected), would it be too much to ask to just overwrite to default when `MARIADB_GALERA_CLUSTER_BOOTSTRAP` is set?

If those two fixes are included we could do this:

```
  galera:
      image: bitnami/mariadb-galera:latest
      hostname: galera{{.Task.Slot}}
      networks:
        - internal
      environment:
        - MARIADB_GALERA_CLUSTER_BOOTSTRAP={{.Task.Slot}}
         - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://galera1
         - MARIADB_ROOT_PASSWORD=PASSWORD
         - MARIADB_GALERA_MARIABACKUP_PASSWORD=PASSWORD

      volumes:
        - /var/data/mariadb/galera{{.Task.Slot}}/db:/bitnami/mariadb
        - /var/data/mariadb/galera{{.Task.Slot}}/config:/opt/bitnami/mariadb/conf/
```

Which means with swarm we can let swarm handle balancing all the node and make sure both the bootstrap and normal nodes are spread out.

With seperated bootstrap and master services, this might lead to both bootstrap and 1 of the masters being put on the same node as the bootstrap. If that node fails everything goes down with it.
