### ISSUE TITLE
Creating a cluster with docker-compose

### ISSUE THREAD

**Issue by gregfr** [bitnami/bitnami-docker-mariadb-galera#16]
Greetings
I'm trying to setup a cluster with docker-compose, but whatever I tried it doesn't seem to ever create the clustering part. The DB itself works ok but no mention of "wsrep" in the log and `show status like "wsrep_cluster_size";` always gives 0.

Here is my compose file:

```yml
  mariadb-galera-006:
        image: mariadb:10.2.15
        container_name: mariadb-galera-006
        hostname: mariadb-galera-006.weave.local
        #        command: --wsrep-new-cluster 
        environment:
                - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
                - MARIADB_GALERA_CLUSTER_NAME=galera_live
                - MARIADB_GALERA_MARIABACKUP_USER=mariabackup_user
                - MARIADB_GALERA_MARIABACKUP_PASSWORD=bkpwd
                - MYSQL_ROOT_PASSWORD=rootpw
                - MARIADB_USER=db_user
                - MARIADB_PASSWORD=dbuserpw
                - MARIADB_DATABASE=mydb
                - CLUSTER_ADDRESS=gcomm://
                - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://
                - NODE_NAME=mariadb-galera-006
        expose:
               - 3306
               - 4444
               - 4567
               - 4568
        dns: 172.17.0.1
        dns_search: weave.local.
        volumes:
               - /home/docker/mysql/mariadb-006:/var/lib/mysql
        networks:
               - weave

networks:
        weave:
          external:
            name: weave
```

I tried with and without commenting the `wsrep-new-cluster ` and the `gcomm://` parts.

What exactly triggers the cluster creation? what am I doing wrong?

Thanks in advance

**Additional information you deem important (e.g. issue happens only occasionally):**

<!-- Any additional information, configuration or data that might be necessary to reproduce the issue. -->

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community                                                                                                                                                                                                                                       [1/521]
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:56 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Weavenet version 2.6.2
VM on Proxmox 5
