### ISSUE TITLE
 Failure to add galera arbitrator to existing Galera Cluster.

### ISSUE THREAD

**Issue by skchoi1234** [bitnami/bitnami-docker-mariadb-galera#25]
**Description**

For Galera Cluster on two hosts, each host was started with `bitnami/mariadb-galera` image, and after that, due to split-brain, it failed to add a Galera arbitrator.

**Steps to reproduce the issue:**

1. [First Step]
   -  The docker network is composed of weave.
   -  I downloaded version 10.5.5 from https://github.com/bitnami/bitnami-docker-mariadb-galera/ and created a Docker image.
2. [Second Step]
   -  First, `mariadb#0` was started for bootstrap, and the command to start it was executed as follows.

```console
$ docker run -d \
        --name mariadb0 \
        --hostname mariadb0.weave.local \
        --net=weave \
        $(weave dns-args) \
        -e MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes \
        -e MARIADB_GALERA_CLUSTER_NAME=xxxxx \
        -e MARIADB_GALERA_MARIABACKUP_USER=sst \
        -e MARIADB_GALERA_MARIABACKUP_PASSWORD=sstpassword \
        -e MARIADB_ROOT_PASSWORD=rootpassword \
        -e MARIADB_USER=proxysql \
        -e MARIADB_PASSWORD=proxysqlpassword \
        -v /home/5gcf-data:/bitnami/mariadb \
        -v /root/5gcf_db/config/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro \
        -v /etc/localtime:/etc/localtime \
        opxepc-svc-host00a:5000/mariadb-galera:10.5.5
```

3. [Third Step]
    - I started `mariadb#2` on another node, and the execution command is as follows.

```console
$docker run -d \
       --name mariadb2 \
       --hostname mariadb2.weave.local \
       --net=weave \
       $(weave dns-args) \
       -e MARIADB_GALERA_CLUSTER_NAME=xxxxx  \
       -e MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb0.weave.local,mariadb1.weave.local,mariadb2.weave.local,mariadb3.weave.local \
       -e MARIADB_GALERA_MARIABACKUP_USER=sst \
       -e MARIADB_GALERA_MARIABACKUP_PASSWORD=sstpassword \
       -e MARIADB_ROOT_PASSWORD=rootpassword  \
       -v /home/5gcf-data:/bitnami/mariadb \
       -v /root/5gcf_db/config/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro \
       -v /etc/localtime:/etc/localtime \
       opxepc-svc-host00a:5000/mariadb-galera:10.5.5
```

4. [Fourth Step]
    - If you check the cluster status after performing steps 2 and 3, the following is displayed normally.

```console
$ docker exec -it mariadb0 mysql -u root -pRcon#2015 -e"show global status like 'wsrep_cluster%'"
+----------------------------+--------------------------------------+
| Variable_name              | Value                                |
+----------------------------+--------------------------------------+
| wsrep_cluster_weight       | 2                                    |
| wsrep_cluster_capabilities |                                      |
| wsrep_cluster_conf_id      | 14                                   |
| wsrep_cluster_size         | 2                                    |
| wsrep_cluster_state_uuid   | 1e5c878a-eb44-11ea-9a96-63de0c89a5b1 |
| wsrep_cluster_status       | Primary                              |
+----------------------------+--------------------------------------+
````

5. [Fifth Step]
   - The existing bitnami image didn't have garbd, so I got the garbd image from docker-percona-xtradb-cluster-garbd.
   - The entrypoint of the downloaded image is as follows.

```console
$ exec /usr/bin/garbd --name ${NODE_NAME} --group ${CLUSTER_NAME} --address gcomm://${CLUSTER_JOIN}
```

Above, NODE_NAME is `mariadb3.weave.local`, CLUSTER_NAME is `xxxx` and Address is `gcomm://mariadb0.weave.local,mariadb1.weave.local,mariadb2.weave.local,mariadb3.weave.local`.

**Describe the results you received:**

```
2020-08-31 16:16:08.198  INFO: CRC-32C: using hardware acceleration.
2020-08-31 16:16:08.198  INFO: Read config:
        daemon:  0
        name:    mariadb3.weave.local
        address: gcomm://mariadb0.weave.local,mariadb1.weave.local,mariadb2.weave.local,mariadb3.weave.local
        group:   xxxxx
        sst:     trivial
        donor:
        options: gcs.fc_limit=9999999; gcs.fc_factor=1.0; gcs.fc_master_slave=yes
        cfg:
        log:

2020-08-31 16:16:08.200  INFO: Using CRC-32C for message checksums.
2020-08-31 16:16:08.200  INFO: gcomm thread scheduling priority set to other:0
2020-08-31 16:16:08.201  INFO: Restoring primary-component from disk successful
2020-08-31 16:16:08.201  INFO: GMCast version 0
2020-08-31 16:16:08.204  WARN: Failed to resolve tcp://mariadb1.weave.local:4567
2020-08-31 16:16:08.205  INFO: (67a0357b, 'tcp://0.0.0.0:4567') listening at tcp://0.0.0.0:4567
2020-08-31 16:16:08.205  INFO: (67a0357b, 'tcp://0.0.0.0:4567') multicast: , ttl: 1
2020-08-31 16:16:08.205  INFO: EVS version 0
2020-08-31 16:16:08.206  INFO: gcomm: connecting to group 'xxxxx', peer 'mariadb0.weave.local:,mariadb1.weave.local:,mariadb2.weave.local:,mariadb3.weave.local:'
2020-08-31 16:16:08.207  INFO: (67a0357b, 'tcp://0.0.0.0:4567') Found matching local endpoint for a connection, blacklisting address tcp://10.32.0.4:4567
2020-08-31 16:16:08.207  INFO: (67a0357b, 'tcp://0.0.0.0:4567') connection established to 2042e270 tcp://10.32.0.3:4567
2020-08-31 16:16:08.207  INFO: (67a0357b, 'tcp://0.0.0.0:4567') turning message relay requesting on, nonlive peers:
2020-08-31 16:16:08.208  INFO: (67a0357b, 'tcp://0.0.0.0:4567') connection established to 337bca04 tcp://10.44.0.0:4567
2020-08-31 16:16:08.708  INFO: declaring 2042e270 at tcp://10.32.0.3:4567 stable
2020-08-31 16:16:08.708  INFO: declaring 337bca04 at tcp://10.44.0.0:4567 stable
2020-08-31 16:16:08.709  INFO: Node 2042e270 state primary
2020-08-31 16:16:08.709  INFO: Current view of cluster as seen by this node
view (view_id(PRIM,2042e270,15)
memb {
        2042e270,0
        337bca04,0
        67a0357b,0
        }
joined {
        }
left {
        }
partitioned {
        }
)
2020-08-31 16:16:08.709  INFO: Save the discovered primary-component to disk
2020-08-31 16:16:08.711  INFO: clear restored view
2020-08-31 16:16:09.207  INFO: gcomm: connected
2020-08-31 16:16:09.207  INFO: Shifting CLOSED -> OPEN (TO: 0)
2020-08-31 16:16:09.207  INFO: New COMPONENT: primary = yes, bootstrap = no, my_idx = 2, memb_num = 3
2020-08-31 16:16:09.207  INFO: STATE EXCHANGE: Waiting for state UUID.
2020-08-31 16:16:09.207  INFO: STATE EXCHANGE: sent state msg: d76d6a59-eb59-11ea-ab3f-56faaa0256e4
2020-08-31 16:16:09.207  INFO: STATE EXCHANGE: got state msg: d76d6a59-eb59-11ea-ab3f-56faaa0256e4 from 0 (mariadb0.weave.local)
2020-08-31 16:16:09.207  INFO: STATE EXCHANGE: got state msg: d76d6a59-eb59-11ea-ab3f-56faaa0256e4 from 1 (mariadb2.weave.local)
2020-08-31 16:16:09.208  INFO: STATE EXCHANGE: got state msg: d76d6a59-eb59-11ea-ab3f-56faaa0256e4 from 2 (mariadb3.weave.local)
2020-08-31 16:16:09.208  INFO: Quorum results:
        version    = 6,
        component  = PRIMARY,
        conf_id    = 14,
        members    = 2/3 (primary/total),
        act_id     = 26,
        last_appl. = -1,
        protocols  = 2/10/4 (gcs/repl/appl),
        group UUID = 1e5c878a-eb44-11ea-9a96-63de0c89a5b1
2020-08-31 16:16:09.208 **_FATAL: gcs/src/gcs_group.cpp:group_check_proto_ver():257: Group requested gcs_proto_ver: 2, max supported by this node: 0.Upgrade the node before joining this group.Need to abort.
2020-08-31 16:16:09.208  INFO: /usr/bin/garbd: Terminated**_.
Aborted
```

**Version**

- Output of `docker version`:

```
(paste your output **here)**
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:46:54 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:45:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

``` 
(paste your output here)
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 25
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay weavemesh
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.18.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 64
 Total Memory: 62.62GiB
 Name: opxepc-svc-host00a
 ID: 34TB:OACA:SWZR:GN76:SFTH:RPLI:XFKH:KWSA:NU4O:LSDP:SOX3:3AYK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  opxepc-svc-host00a:5000
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-ip6tables is disabled

```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
Not used.
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by dani8art** [comment]
Hi @skchoi1234 thanks for opening this issue, 

It seems the issue is related to the compatibility with the version of the `gcs_proto_ver` between `docker-percona-xtradb-cluster-garbd` and our images. 

Please, could you share also the entire command to deploy the third node so I can try to reproduce the issue on my side?

**Comment by skchoi1234** [comment]
First of all, due to lack of equipment, I built a Galera Cluster with 2 nodes, and ran the Galera Arbitrator (garbd) Image on the first node.
And  the contents of the downloaded Dockerfile are as follows.

----------------

FROM debian:stretch-slim
ENV VERSION 5.7.30-31.43
ENV DEBIAN_FRONTEND noninteractive
RUN groupadd -g 1001 mysql && \
    useradd -u 1001 -r -g 1001 -s /sbin/nologin -c "Default Application User" mysql && \
    apt-get update -qq && apt-get install -qqy --no-install-recommends \
    apt-transport-https ca-certificates pwgen wget gnupg2 && \
    wget https://repo.percona.com/apt/percona-release_0.1-6.stretch_all.deb && \
    dpkg -i percona-release_0.1-6.stretch_all.deb && \
    rm -rf *.deb && \
    rm -rf /var/lib/apt/lists/*
RUN apt-get update -qq
RUN apt-get -y install vim net-tools iputils-ping
RUN apt-get update -qq
RUN apt-get install -qqy --force-yes netcat-openbsd libboost-program-options1.62.0
RUN wget https://repo.percona.com/apt/pool/main/p/percona-xtradb-cluster-5.7/percona-xtradb-cluster-garbd-5.7_${VERSION}-1.stretch_amd64.deb
RUN dpkg -i percona-xtradb-cluster-garbd-5.7_${VERSION}-1.stretch_amd64.deb
RUN rm -rf *.deb
RUN rm -rf /var/lib/apt/lists/*

COPY docker-entrypoint.sh /entrypoint.sh
RUN chmod a+x /entrypoint.sh

EXPOSE 3306 4444 4567 4568

ENTRYPOINT ["/entrypoint.sh"]
#USER 1001
CMD [""]

----------------------------
The contents of USER 1001 are commented out as a permission problem.

And the content of entrypoint.sh is as below.

-------------------
#!/bin/bash
if [ -z "${CLUSTER_NAME}" ]; then
    echo >&2 'Error:  You need to specify CLUSTER_NAME'
    exit 1
fi

if [ -z "${CLUSTER_JOIN}" ]; then
    echo >&2 'Error:  You need to specify CLUSTER_ADDRESS'
    exit 1
fi

if [ -z "${NODE_NAME}" ]; then
    NODE_NAME=`hostname`
fi

if [ -z "${LOG_FILE}" ]; then
    LOG_FILE="/dev/stdout"
fi

exec /usr/bin/garbd --name ${NODE_NAME} --group ${CLUSTER_NAME} --address gcomm://${CLUSTER_JOIN}

-----------------------

And the contents of docker run are as follows.

----------------------

#!/bin/bash

docker run -d \
       --name mariadb3 \
       --hostname mariadb3.weave.local \
       --net=weave \
       $(weave dns-args) \
       -e CLUSTER_NAME=xxxxx \
       -e CLUSTER_JOIN=mariadb0.weave.local,mariadb1.weave.local,mariadb2.weave.local,mariadb3.weave.local \
       -v /etc/localtime:/etc/localtime \
       opxepc-svc-host00a:5000/5.7.43

--------------------

**Comment by dani8art** [comment]
You should have the same config in all node for GCS and GCOMM more info [here](https://manpages.debian.org/stretch/galera-arbitrator-3/garbd.8) In this case it is complaining about `gcs_proto_ver` you should be able to configure it using [this](https://galeracluster.com/library/documentation/arbitrator.html) and [this](https://galeracluster.com/library/documentation/galera-parameters.html)

**Comment by skchoi1234** [comment]
I have confirmed what you said. And I also checked the source(https://github.com/codership/galera/blob/3.x/gcs/src/gcs_group.cpp).

As a result of my confirmation, I am judged to be a GCOMM Address's number problem.

However, when configuring Galera Cluster in container, GCOMM  Address of Bootstrap Container has to be empty.

Looking at the source, it seems that node.LEVEL has fewer but fewer than quorum.LEVEL.

---
static void
group_check_proto_ver(gcs_group_t* group)
{
    assert(group->quorum.primary); // must be called only on primary CC

    gcs_node_t& node(group->nodes[group->my_idx]);
    bool fail(false);

#define GROUP_CHECK_NODE_PROTO_VER(LEVEL)                               \
    if (node.LEVEL < group->quorum.LEVEL) {                             \
        gu_fatal("Group requested %s: %d, max supported by this node: %d." \
                 "Upgrade the node before joining this group."          \
                 "Need to abort.",                                      \
                 #LEVEL, group->quorum.LEVEL, node.LEVEL);              \
        fail = true;                                                    \
    }

    GROUP_CHECK_NODE_PROTO_VER(gcs_proto_ver);
    GROUP_CHECK_NODE_PROTO_VER(repl_proto_ver);
    GROUP_CHECK_NODE_PROTO_VER(appl_proto_ver);

#undef GROUP_CHECK_NODE_PROTO_VER

    if (fail) gu_abort();
}
---

I wonder if this part is necessary when extracting container-based Galera Cluster.
Anyway, I will check the test a little more and write again to see if there is a plan.

**Comment by dani8art** [comment]
> However, when configuring Galera Cluster in container, GCOMM Address of Bootstrap Container has to be empty.

You can try to use this `MARIADB_GALERA_CLUSTER_BOOTSTRAP` in a combination with `MARIADB_GALERA_CLUSTER_ADDRESS` to set up the cluster. 

Yes, I think it should be called only in primary nodes, so maybe there is a way to say this image to don't try to be a primary one but an arbiter.

**Comment by skchoi1234** [comment]
Um.. I will try to test again after obtaining  other garbd images. 
Of course, I will also test the part you mentioned.
There is an presentation tomorrow, so I will conduct the test after the next week.

**Comment by skchoi1234** [comment]
I tested by including MARIADB_GALERA_CLUSTER_ADDRESS mentioned previously in MARIADB_GALERA_CLUSTER_BOOTSTRAP, but the result was similarly failed.
What's the other way?
I wonder if Bitnami is considering Galera Arbitrator.

**Comment by dani8art** [comment]
Hi @skchoi1234,

The team has been checking Galera Arbitrator and we consider it could be a good new feature. We consider this as a low priority feature since it is an optional component, from a cluster point of view we could avoid it. We just created an internal task to add this new container and included it in our backlog. As the impact of the feature is limited and not critical, we can’t provide an ETA. Nevertheless, it will be considered for future application versions.

Thank you so much for your feedback!

**Comment by skchoi1234** [comment]
Thank you for your consideration.
It is also a burden for small businesses like us to have 3 Database Volumes each.
I will check again when the version is released later.

**Comment by Douglas-Hsieh** [comment]
I'm not using bitnami, but I had the same exact issue and resolved it when I switched installs from
galera-arbitrator-3 to galera-arbitrator-4

**Comment by skchoi1234** [comment]
I couldn't figure out the exact cause. When I match the Mariadb Version(10.5), it works normally.
Thank you to everyone who helped.

**Comment by dani8art** [comment]
Thank you all for keeping us updated, happy to see they worked!

**Comment by tholu** [comment]
Ran into the same problem in a native Debian installation, using galera-arbitrator-4 instead of galera-arbitrator-3 helped me as well (and updating Debian stretch to Debian buster beforehand).

**Comment by LefterisL** [comment]
I'm also using galera-arbitrator-4 and connecting without an issue, although as soon as I turn on SSL and with the appropriate options to the arbitrator the arbitrator  just keeps timing out. Has anyone connected the garbt with ssl ?

**Comment by javsalgar** [comment]
Hi,

We would like to reproduce the issue, could you provide the values you used?.

**Comment by LefterisL** [comment]
Absolutely, here is part of the compose file

```
  #Node 0
  mariadb-galera-0:
    image: bitnami/mariadb-galera:latest
    hostname: mariadb-galera-0
    ports:
      - 13306:3306
    environment:
      - MARIADB_ENABLE_TLS=yes
      - MARIADB_TLS_CERT_FILE=/bitnami/mariadb/certs/cert.pem
      - MARIADB_TLS_KEY_FILE=/bitnami/mariadb/certs/key.pem
      - MARIADB_TLS_CA_FILE=/bitnami/mariadb/certs/ca.pem
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_CLUSTER_NAME=s_cluster
      - MARIADB_GALERA_MARIABACKUP_USER=XXX_bk
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=XXX_bk
      - MARIADB_ROOT_PASSWORD=test
      - MARIADB_USER=XXX
      - MARIADB_PASSWORD=XXXXXX
      - MARIADB_DATABASE=database
      - MARIADB_REPLICATION_USER=XXX_repl
      - MARIADB_REPLICATION_PASSWORD=XXXX_repl_pass
      - MARIADB_GALERA_NODE_ADDRESS=mariadb-galera-0
    networks:
      - app-network
    volumes:
      - ./docker/ca-cert.pem:/bitnami/mariadb/certs/ca.pem:ro
      - ./docker/server-cert.pem:/bitnami/mariadb/certs/cert.pem:ro
      - ./docker/server-key.pem:/bitnami/mariadb/certs/key.pem:ro
      - ./docker/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - ./docker/percistence_0/:/bitnami/mariadb

# Node 1
  mariadb-galera-1:
    image: bitnami/mariadb-galera:latest
    hostname: mariadb-galera-1
    links:
      - mariadb-galera-0
    ports:
      - 23306:3306
    environment:
      - MARIADB_ENABLE_TLS=yes
      - MARIADB_TLS_CERT_FILE=/bitnami/mariadb/certs/cert.pem
      - MARIADB_TLS_KEY_FILE=/bitnami/mariadb/certs/key.pem
      - MARIADB_TLS_CA_FILE=/bitnami/mariadb/certs/ca.pem
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=no
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera-0:4567,mariadb-galera-1:4567,mariadb-galera-arb:4567
      - MARIADB_GALERA_CLUSTER_NAME=s_cluster
      - MARIADB_GALERA_MARIABACKUP_USER=XXX_bk
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=XXX_bk
      - MARIADB_ROOT_PASSWORD=test
      - MARIADB_REPLICATION_USER=XXX_repl
      - MARIADB_REPLICATION_PASSWORD=XXXX_repl_pass
      - MARIADB_GALERA_NODE_ADDRESS=mariadb-galera-1
    networks:
      - app-network
    volumes:
      - ./docker/ca-cert.pem:/bitnami/mariadb/certs/ca.pem:ro
      - ./docker/server-cert.pem:/bitnami/mariadb/certs/cert.pem:ro
      - ./docker/server-key.pem:/bitnami/mariadb/certs/key.pem:ro
      - ./docker/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - ./docker/percistence_1/:/bitnami/mariadb

# Arbitrator
  mariadb-galera-arb:
    build:
      context: ./arbitrator
      dockerfile: Dockerfile
    hostname: mariadb-galera-arb
    links:
      - mariadb-galera-0
    ports:
      - 53306:3306
    environment:
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera-0:4567,mariadb-galera-1:4567,mariadb-galera-arb:4567
      - MARIADB_GALERA_CLUSTER_NAME=s_cluster
      - MARIADB_GALERA_CLUSTER_OPTIONS=socket.ssl_key=/etc/ssl/galera/server-key.pem;socket.ssl_cert=/etc/ssl/galera/server-cert.pem;socket.ssl_ca=/etc/ssl/galera/ca-cert.pem;socket.ssl_cipher=AES128-SHA
    networks:
      - app-network
    volumes:
      - ./docker/ca-cert.pem:/etc/ssl/galera/ca-cert.pem:ro
      - ./docker/server-cert.pem:/etc/ssl/galera/server-cert.pem:ro
      - ./docker/server-key.pem:/etc/ssl/galera/server-key.pem:ro

```

Dockerfile
```
FROM ubuntu:18.04

COPY entrypoint.sh /entrypoint.sh

RUN apt-get update && apt-get install -y gnupg2
RUN apt-get install -y software-properties-common
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv BC19DDBA
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv D669017EBC19DDBA
RUN add-apt-repository 'deb https://releases.galeracluster.com/galera-4/ubuntu bionic main'
RUN add-apt-repository 'deb https://releases.galeracluster.com/mysql-wsrep-5.7/ubuntu bionic main'
RUN apt-get update
RUN apt-get install -y galera-4 galera-arbitrator-4 rsync

RUN chmod +x /entrypoint.sh

EXPOSE 4567

ENTRYPOINT  /entrypoint.sh
CMD entrypoint.sh

```

Entrypoint
```
#!/bin/bash

set -e

echo 'Starting arbitrator...'
[ -n "$MARIADB_GALERA_CLUSTER_ADDRESS" ] || (echo '$MARIADB_GALERA_CLUSTER_ADDRESS is not defined' && exit 1)

echo "${MARIADB_GALERA_CLUSTER_NAME}"
echo "${MARIADB_GALERA_CLUSTER_ADDRESS}"
echo "${MARIADB_GALERA_CLUSTER_OPTIONS}"

garbd --group="${MARIADB_GALERA_CLUSTER_NAME}" --address="${MARIADB_GALERA_CLUSTER_ADDRESS}" --option="${MARIADB_GALERA_CLUSTER_OPTIONS}"

```

All the certs are the same across the nodes + the garbd. 
The custom conf I think is irrelevant but
```
[mysqld]
max_allowed_packet=510M
bind-address = 0.0.0.0
default_authentication_plugin = mysql_native_password
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

```

If you need anything else do let me know or if I could help somehow. Thank you
