### ISSUE TITLE
Fresh Galera cluster startup with docker-compose fails

### ISSUE THREAD

**Issue by niom** [bitnami/bitnami-docker-mariadb-galera#26]
I try to create a galera cluster with docker-compose. I run the galera cluster inside a Vagrant machine (debian 10). When I start the galera cluster with docker-compose the mariadb starts and stops after couple of seconds. When I run docker-compose up again without first calling docker-compose down the cluster starts normally.

Here's the docker-compose.yml I'm usings

```
version: '2'

services:
    db1:
        image: bitnami/mariadb-galera:10.4.12-debian-10-r106
        container_name: db1
        environment:
            - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
            - MARIADB_GALERA_CLUSTER_NAME=my-galera
            - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://db1,db2,db3
            - MARIADB_GALERA_MARIABACKUP_USER=root
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=myrootpassword
            - MARIADB_ROOT_PASSWORD=myrootpassword
            - MARIADB_USER=galera
            - MARIADB_PASSWORD=mygalerapassword
            - MARIADB_DATABASE=mydb
        ports:
            - 3311:3306
        networks:
            - cluster
    db2:
        image: bitnami/mariadb-galera:10.4.12-debian-10-r106
        container_name: db2
        environment:
            - MARIADB_GALERA_CLUSTER_NAME=my-galera
            - MARIADB_GALERA_MARIABACKUP_USER=root
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=myrootpassword
            - MARIADB_ROOT_PASSWORD=myrootpassword
            - MARIADB_USER=galera
            - MARIADB_PASSWORD=mygalerapassword
            - MARIADB_DATABASE=mydb
        ports:
            - 3312:3306
        networks:
            - cluster

    db3:
        image: bitnami/mariadb-galera:10.4.12-debian-10-r106
        container_name: db3
        environment:
            - MARIADB_GALERA_CLUSTER_NAME=my-galera
            - MARIADB_GALERA_MARIABACKUP_USER=root
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=myrootpassword
            - MARIADB_ROOT_PASSWORD=myrootpassword
            - MARIADB_USER=galera
            - MARIADB_PASSWORD=mygalerapassword
            - MARIADB_DATABASE=mydb
        ports:
            - 3313:3306
        networks:
            - cluster

networks:
    cluster:
```

running: docker-compose up 
will print out following log:
```
docker-compose up
Creating network "vagrant_cluster" with the default driver
Creating db1 ... done
Creating db2 ... done
Creating db3 ... done
Attaching to db2, db1, db3
db2    |  13:08:49.37
db2    |  13:08:49.37 Welcome to the Bitnami mariadb-galera container
db1    |  13:08:49.37
db1    |  13:08:49.37 Welcome to the Bitnami mariadb-galera container
db1    |  13:08:49.38 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
db2    |  13:08:49.38 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
db2    |  13:08:49.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
db1    |  13:08:49.38 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
db1    |  13:08:49.38
db2    |  13:08:49.38
db1    |  13:08:49.38 INFO  ==> ** Starting MariaDB setup **
db2    |  13:08:49.39 INFO  ==> ** Starting MariaDB setup **
db3    |  13:08:49.41
db3    |  13:08:49.42 Welcome to the Bitnami mariadb-galera container
db3    |  13:08:49.42 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
db3    |  13:08:49.42 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
db3    |  13:08:49.42
db3    |  13:08:49.42 INFO  ==> ** Starting MariaDB setup **
db1    |  13:08:49.44 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
db1    |  13:08:49.45 INFO  ==> Initializing mariadb database...
db2    |  13:08:49.46 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
db2    |  13:08:49.47 INFO  ==> Initializing mariadb database...
db3    |  13:08:49.49 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
db3    |  13:08:49.49 INFO  ==> Initializing mariadb database...
db2    |  13:08:51.93 INFO  ==> Starting mariadb in background
db1    |  13:08:51.94 INFO  ==> Starting mariadb in background
db3    |  13:08:51.95 INFO  ==> Starting mariadb in background
db2    |  13:08:53.07 INFO  ==> Stopping mariadb
db3    |  13:08:53.09 INFO  ==> Stopping mariadb
db1    |  13:08:53.10 INFO  ==> Stopping mariadb
db3 exited with code 1
db2 exited with code 1
db1 exited with code 1
```

When running the docker-compose up again the instance starts without a problem
docker-compose up --> 
```
Starting db1 ... done
Starting db3 ... done
Starting db2 ... done
Attaching to db1, db3, db2
db1    |  13:16:45.70
db1    |  13:16:45.70 Welcome to the Bitnami mariadb-galera container
db1    |  13:16:45.71 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
db1    |  13:16:45.71 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
db1    |  13:16:45.71
db1    |  13:16:45.71 INFO  ==> ** Starting MariaDB setup **
db3    |  13:16:45.73
db3    |  13:16:45.73 Welcome to the Bitnami mariadb-galera container
db3    |  13:16:45.73 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
db3    |  13:16:45.73 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
db3    |  13:16:45.73
db3    |  13:16:45.73 INFO  ==> ** Starting MariaDB setup **
db2    |  13:16:45.75
db2    |  13:16:45.75 Welcome to the Bitnami mariadb-galera container
db2    |  13:16:45.75 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb-galera
db2    |  13:16:45.75 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb-galera/issues
db2    |  13:16:45.76
db2    |  13:16:45.76 INFO  ==> ** Starting MariaDB setup **
db1    |  13:16:45.79 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
db1    |  13:16:45.80 INFO  ==> Initializing mariadb database...
db3    |  13:16:45.81 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
db1    |  13:16:45.81 INFO  ==> Persisted data detected. Restoring...
db3    |  13:16:45.81 INFO  ==> Initializing mariadb database...
db1    |  13:16:45.82 INFO  ==> ** MariaDB setup finished! **
db1    |
db3    |  13:16:45.83 INFO  ==> Persisted data detected. Restoring...
db2    |  13:16:45.83 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars..
db3    |  13:16:45.84 INFO  ==> ** MariaDB setup finished! **
db3    |
db2    |  13:16:45.84 INFO  ==> Initializing mariadb database...
db2    |  13:16:45.86 INFO  ==> Persisted data detected. Restoring...
db2    |  13:16:45.87 INFO  ==> ** MariaDB setup finished! **
db2    |
db1    |  13:16:45.90 INFO  ==> ** Starting MariaDB **
db3    |  13:16:45.91 INFO  ==> ** Starting MariaDB **
db2    |  13:16:45.96 INFO  ==> ** Starting MariaDB **
db1    | 2020-09-01 13:16:46 0 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.4.12-MariaDB-log) starting as process 1 ...
db1    | 2020-09-01 13:16:46 0 [Note] WSREP: Loading provider /opt/bitnami/mariadb/lib/libgalera_smm.so initial position: 00000000-0000-0000-0000-000000000000:-1
db1    | wsrep loader: [INFO] wsrep_load(): loading provider library '/opt/bitnami/mariadb/lib/libgalera_smm.so'
db1    | wsrep loader: [INFO] wsrep_load(): Galera 4.3(r0) by Codership Oy <info@codership.com> loaded successfully.
db1    | 2020-09-01 13:16:46 0 [Note] WSREP: CRC-32C: using hardware acceleration.
db1    | 2020-09-01 13:16:46 0 [Note] WSREP: Found saved state: 4832ce63-ec54-11ea-9209-4f506aa864b7:8, safe_to_bootstrap: 1
db1    | 2020-09-01 13:16:46 0 [Note] WSREP: GCache DEBUG: opened preamble:
db1    | Version: 2
```

if the cluster is run down: docker-compose down
and started again: docker-compose up

the started and shutdown behaviour occurs again.

I also tried this on my laptop (OSX), but the docker-compose failed with the same behaviour with the first start up.

Am I missing something from the configuration?

**Comment by niom** [comment]
As always these kinds of problems lie between the chair and the keyboard.

I converted the example galera docker start script to docker compose and like a magic it started up without an error. After couple of iterations against my own configuration the problem is with MARIABACKUP parameters. The backup user cannot exist and I made a mistake for using root and root password.

The incorrect configuration.
```
            - MARIADB_ROOT_PASSWORD=myrootpassword
            - MARIADB_GALERA_MARIABACKUP_USER=root
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=myrootpassword
```

Changing the backup user and password to non colliding user, everything works at the start up

So here's the working configuration
```
version: '2'

services:
    db1:
        image: bitnami/mariadb-galera:10.4.12-debian-10-r106
        container_name: db1
        environment:
            - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
            - MARIADB_GALERA_CLUSTER_NAME=my-galera
            - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://db1,db2,db3
            - MARIADB_GALERA_MARIABACKUP_USER=root
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=myrootpassword
            - MARIADB_ROOT_PASSWORD=myrootpassword
            - MARIADB_USER=galera
            - MARIADB_PASSWORD=mygalerapassword
            - MARIADB_DATABASE=mydb
        ports:
            - 3311:3306
        networks:
            - cluster
    db2:
        image: bitnami/mariadb-galera:10.4.12-debian-10-r106
        container_name: db2
        environment:
            - MARIADB_GALERA_CLUSTER_NAME=my-galera
            - MARIADB_GALERA_MARIABACKUP_USER=root
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=myrootpassword
            - MARIADB_ROOT_PASSWORD=myrootpassword
            - MARIADB_USER=galera
            - MARIADB_PASSWORD=mygalerapassword
            - MARIADB_DATABASE=mydb
        ports:
            - 3312:3306
        networks:
            - cluster

    db3:
        image: bitnami/mariadb-galera:10.4.12-debian-10-r106
        container_name: db3
        environment:
            - MARIADB_GALERA_CLUSTER_NAME=my-galera
            - MARIADB_GALERA_MARIABACKUP_USER=my_galera_backup
            - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_galera_backup_password
            - MARIADB_ROOT_PASSWORD=myrootpassword
            - MARIADB_USER=galera
            - MARIADB_PASSWORD=mygalerapassword
            - MARIADB_DATABASE=mydb
        ports:
            - 3313:3306
        networks:
            - cluster

networks:
    cluster:
```
