### ISSUE TITLE
Running a multi-master galera cluster with docker-compose on docker desktop

### ISSUE THREAD

**Issue by samuelgautier** [bitnami/bitnami-docker-mariadb-galera#44]
**Description**

To get a running multi-master Galera cluster with docker-compose on docker-desktop, i had to perform the following tasks : 

1- Execute "docker-compose up" with all environment variables except MARIADB_GALERA_CLUSTER_ADDRESS=yes (comment this line if not already done)
2- Stop the containers
3- Edit the file "./data/db/data/grastate.dat" to pass the variable "safe_to_bootstrap" to 1 and restart "docker-compose up".
4- Stop the containers again
5- Uncomment the line MARIADB_GALERA_CLUSTER_ADDRESS=yes and restart "docker-compose up". 
6- Stopping the containers 
7- Comment on the following 3 environment variables : MARIADB_GALERA_CLUSTER_BOOTSTRAP, MARIADB_GALERA_CLUSTER_ADDRESS, MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes and restart docker-compose up

Otherwise it was impossible to get the cluster running !
Maybe i missed something or did something wrong !! I just want to understand what was going wrong ;)

**Steps to reproduce the issue:**

here is my docker-compose.yaml 

```
version: '2.1'

services:
  mariadb-galera-first:
    image: 'docker.io/bitnami/mariadb-galera:latest'
    ports:
      - '3307:3306'
      - '4444:4444'
      - '4567:4567'
      - '4568:4568'
    volumes:
      - ./data/db:/bitnami/mariadb
    environment:
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_CLUSTER_ADDRESS=yes
      - MARIADB_GALERA_FORCE_SAFETOBOOTSTRAP=yes
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_MARIABACKUP_USER=mariabackupuser
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=mariabackuppassword
      - MARIADB_ROOT_PASSWORD=P4SSW0RD123
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=password
      - MARIADB_DATABASE=my_database
      - MARIADB_REPLICATION_USER=rep_user
      - MARIADB_REPLICATION_PASSWORD=P4SSW0RD123
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  mariadb-galera-second:
    image: 'docker.io/bitnami/mariadb-galera:latest'
    ports:
      - '3308:3306'
      - '4445:4444'
      - '4569:4567'
      - '4570:4568'
    volumes:
      - ./data/db2:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera-first:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=mariabackupuser
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=mariabackuppassword
      - MARIADB_ROOT_PASSWORD=P4SSW0RD123
      - MARIADB_REPLICATION_USER=rep_user
      - MARIADB_REPLICATION_PASSWORD=P4SSW0RD123
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      - mariadb-galera-first   
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1


# volumes:
#   mariadb_galera_data:
#     driver: local

```
**Describe the results you received:**

I've got several issues and error messages at each step telling me that i had to change the "safe_to_bootstrap" value, that the Backend URI was wrong beacause of "MARIADB_GALERA_CLUSTER_ADDRESS=yes" and so on.

**Describe the results you expected:**

A galera cluster up & running at first time !

**Additional information you deem important (e.g. issue happens only occasionally):**

Following the different steps explained above, i can get a healthy multi-master Cluster that i can stop and restart without any problem with persistent data.

**Version**

- Output of `docker version`:
```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:14:16 2020
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 24.78GiB
 Name: docker-desktop
 ID: 3V4F:67CX:K472:YQLW:ML2Q:J6JV:UGYK:MNNC:ZTJC:DKRZ:2XVW:7HJT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Windows 10

**Comment by juan131** [comment]
Hi @samuelgautier 

I just followed [this guide](https://github.com/bitnami/bitnami-docker-mariadb-galera#setting-up-a-multi-master-cluster), translating the instructions to the `docker-compose.yaml` below:

```yaml
version: '2.3'

services:
  mariadb-galera-0:
    image: docker.io/bitnami/mariadb-galera:latest
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=galera
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_ROOT_PASSWORD=P4SSW0RD123
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_DATABASE=my_database
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    volumes:
      - 'mariadb_galera_data_0:/bitnami/mariadb'
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  mariadb-galera-1:
    image: docker.io/bitnami/mariadb-galera:latest
    command:
      - bash
      - -ec
      - |
          # Wait 20 seconds to guarantee creation order
          sleep 20
          exec /opt/bitnami/scripts/mariadb-galera/entrypoint.sh /opt/bitnami/scripts/mariadb-galera/run.sh
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://mariadb-galera-0:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_ROOT_PASSWORD=P4SSW0RD123
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    volumes:
      - 'mariadb_galera_data_1:/bitnami/mariadb'
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb-galera/healthcheck.sh']
      start_period: 20s
      interval: 15s
      timeout: 5s
      retries: 6
    depends_on:
      - mariadb-galera-0

volumes:
  mariadb_galera_data_0:
    driver: local
  mariadb_galera_data_1:
    driver: local
```

Since Docker Compose doesn't provide a way to guarantee order creation for the containers, I did a little trick to sleep 20 seconds the second container.
