### ISSUE TITLE
Access denied for user 'root'@wrong IP - mysqld signal 11 on node sync

### ISSUE THREAD

**Issue by LefterisL** [bitnami/bitnami-docker-mariadb-galera#48]
**Description**

Hello, I am able to setup a cluster of 4 nodes (+ arbitrator) on a windows machine on a single docker compose file. However when I try to do something similar on 2 different servers I'm hitting a brick wall. 

The first weird issue is that once the first bootstrap node is up and running I'm getting
```
[Warning] Access denied for user 'root'@'172.25.0.1' (using password: YES)
```
The weird thing here is that the container ip is not `172.25.0.1` but `172.25.0.2`.
Output of `getent hosts` from inside the container
```
docker exec -it galera_mariadb-galera-165_1 getent hosts               
127.0.0.1       localhost
127.0.0.1       localhost ip6-localhost ip6-loopback
172.25.0.2      cfc9d22197a1
```

Why would it try to connect to `172.25.0.1` ? The node works fine however, allowing me to connect via phpmyadmin also and 
```
+---------------------------+--------------------------------------+
| Variable_name             | Value                                |
+---------------------------+--------------------------------------+
| wsrep_local_state_comment | Synced                               |
| wsrep_cluster_size        | 1                                    |
| wsrep_cluster_state_uuid  | 87efe080-be3d-11eb-871d-769200e831d2 |
| wsrep_cluster_status      | Primary                              |
| wsrep_connected           | ON                                   |
+---------------------------+--------------------------------------+

```

Moving on to the other server now I init the 2nd node and while it looks like it's syncing ( or at least trying too since there are incoming logs on the other one ) after a few seconds it's exiting with `[ERROR] mysqld got signal 11 ;`

Both of those server IPs are public (i'll be replacing the some digits for obvious reasons). 
Bootstraping host => `165.XXX.XXX.XXX`
Following up host => `178.XXX.XXX.XXX`

I'll leave some files at the end with the complete logs from both nodes

**Steps to reproduce the issue:**

1. Bootstraping Host Docker Compose
```
version: '3.1'
services:
  mariadb-galera-165:
    image: bitnami/mariadb-galera:latest
    ports:
      - 3306:3306
      - 4444:4444
      - 4567:4567
      - 4568:4568
    environment:
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_GALERA_CLUSTER_NAME=k_cluster
      - MARIADB_ROOT_PASSWORD=test
      - MARIADB_USER=test_user
      - MARIADB_PASSWORD=test_passowrd
      - MARIADB_GALERA_MARIABACKUP_USER=backupuser
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backuppassword
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
      - MARIADB_GALERA_NODE_ADDRESS=165.XXX.XXX.XXX
      - MARIADB_DATABASE=test_db
    volumes:
      - ./docker/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - db:/bitnami/mariadb
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
    
#Volumes
volumes:
  db:
    driver: local
```
2. Follow up node Docker Compose
```
version: '3.1'
services:
  mariadb-galera-178:
    image: bitnami/mariadb-galera:latest
    ports:
      - 3306:3306
      - 4444:4444
      - 4567:4567
      - 4568:4568
    environment:
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://165.XXX.XXX.XXX:4567,0.0.0.0:4567
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=no
      - MARIADB_GALERA_CLUSTER_NAME=k_cluster
      - MARIADB_ROOT_PASSWORD=test
      - MARIADB_USER=test_user
      - MARIADB_PASSWORD=test_passowrd
      - MARIADB_GALERA_MARIABACKUP_USER=backupuser
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=backuppassword
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
      - MARIADB_GALERA_NODE_ADDRESS=178.XXX.XXX.XXX
    volumes:
      - ./docker/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - db:/bitnami/mariadb
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
    
#Volumes
volumes:
  db:
    driver: local
```
3. my_custom.cnf file 
```
[mysqld]
bind-address = 0.0.0.0
default_authentication_plugin = mysql_native_password
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
```

**Describe the results you received:**

Cluster not syncing with the 2nd node to crash after a few seconds

**Describe the results you expected:**

Cluster to sync and stay in sync

**Additional information you deem important (e.g. issue happens only occasionally):**

It's strange because when using 1 composer file and running it all are connecting fine with each other. The only differences actually here are the IPs which in the case of the 1 docker compose file I'm using the hostnames of each service.

**Version**

- Output of `docker version`:

```
Docker version 20.10.6, build 370c289 on both hosts ( Ubuntu 18.04 )
```

- Output of `docker info`:

```
Bootstrap node => 
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 6
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.0-210-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 992.2MiB
 Name: lamp
 ID: QBRQ:SA5R:GPOC:YLYZ:R2TO:D4CI:FAKS:C2VX:EPW2:3LW3:5KQK:2L56
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support



Follow up node ->
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.7.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 1
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-142-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 985.1MiB
 Name: i
 ID: PTBX:5WJT:BCIT:VTJ4:E4CI:TBQJ:NQT4:5USU:OI7A:W6YH:SI2D:YJN4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
Host
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

Follow up
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Before every run I do `docker-compose down && docker volume rm galera_db && docker-compose up --build` to make sure nothing is left from previous runes etc.

[bootstrapNode.txt](https://github.com/bitnami/bitnami-docker-mariadb-galera/files/6548408/bootstrapNode.txt)
[followupNode.txt](https://github.com/bitnami/bitnami-docker-mariadb-galera/files/6548409/followupNode.txt)
