### ISSUE TITLE
How to Create Mariadb-Galera-Cluster with Docker-Compose

### ISSUE THREAD

**Issue by phonepasit9** [bitnami/bitnami-docker-mariadb-galera#60]
**Description**

I want to create Docker Swarm and Mariadb-galera-cluster so i have issue how to create docker-compose maria-galera

**Steps to reproduce the issue:**

1. This is my docker-compose name : maria-galera.yml
```
version: '3.5'

networks:
  marianet:
    driver: overlay

services:
  mariadb-galera-1:
    image: 'bitnami/mariadb-galera:latest'
    environment:
            #      - constraint:node==wk1
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - marianet
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==wk1"

  mariadb-galera-2:
    image: 'bitnami/mariadb-galera:latest'
    environment:
            #      - constraint:node==wk2
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - marianet
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==wk2"

  mariadb-galera-3:
    image: 'bitnami/mariadb-galera:latest'
    environment:
            #      - constraint:node==wk3
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - marianet
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==wk3"

  mariadb-galera-4:
    image: 'bitnami/mariadb-galera:latest'
    environment:
            #      - constraint:node==wk4
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - marianet
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==wk4"

```

I try not working 
```
version: '3.5'

networks:
  marianet:
    driver: overlay

services:
  mariadb-galera-1:
    image: 'bitnami/mariadb-galera:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=test
      - REPLICATION_PASSWORD=test
      - MARIADB_DATABASE=maria
      - MARIADB_USER=maria
      - MARIADB_PASSWORD=test
      - GALERA=On
      - NODE_NAME=wk1
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://
    command: --wsrep-new-cluster	    
    networks:
      - marianet
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==wk1"

		  
  mariadb-galera-2:
    image: 'bitnami/mariadb-galera:latest'
    environment:
      - REPLICATION_PASSWORD=test
      - GALERA=On
      - NODE_NAME=wk2
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://wk1
    networks:
      - marianet
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==wk2"



  mariadb-galera-3:
    image: 'bitnami/mariadb-galera:latest'
    environment:
      - REPLICATION_PASSWORD=test
      - GALERA=On
      - NODE_NAME=wk3
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://wk1
    networks:
      - marianet
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==wk3"



  mariadb-galera-4:
    image: 'bitnami/mariadb-galera:latest'
    environment:
      - REPLICATION_PASSWORD=test
      - GALERA=On
      - NODE_NAME=wk4
      - CLUSTER_NAME=maria_cluster
      - CLUSTER_ADDRESS=gcomm://wk1
    networks:
      - marianet
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.hostname==wk4"

```

- Output Not Work:

```
root@mg1:~# docker stack deploy -c  maria-galera1.yml galera
Creating network galera_marianet
Creating service galera_mariadb-galera-1
Creating service galera_mariadb-galera-2
Creating service galera_mariadb-galera-3
Creating service galera_mariadb-galera-4
root@mg1:~#
root@mg1:~# docker service ls
ID             NAME                      MODE         REPLICAS   IMAGE                             PORTS
f6tag23sms8w   galera_mariadb-galera-1   replicated   0/1        bitnami/mariadb-galera:latest
p10qqxjkbd9m   galera_mariadb-galera-2   replicated   0/1        bitnami/mariadb-galera:latest
p3ppu6r5rn6y   galera_mariadb-galera-3   replicated   0/1        bitnami/mariadb-galera:latest
p6wfgydlhta6   galera_mariadb-galera-4   replicated   0/1        bitnami/mariadb-galera:latest
a09093q96suw   vm_visualizer             replicated   1/1        dockersamples/visualizer:stable   *:8080->8080/tcp

```
Please help me ? Thank you. I just beginner

**Comment by migruiz4** [comment]
Hi @phonepasit9,

I would recommend you to have a look at the [MariaDB Galera Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera), as it might be an alternative to what you are looking for.

If you want to continue with your approach,  I'd suggest try using the following:

```yaml
version: '3.5'

networks:
  marianet:
    driver: overlay

services:
  mariadb-galera-bootstrap:
    image: 'bitnami/mariadb-galera:latest'
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=galera
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_ROOT_PASSWORD=my_root_password
      - MARIADB_GALERA_CLUSTER_BOOTSTRAP=yes
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_DATABASE=my_database
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    networks:
      - marianet
    deploy:
      replicas: 1
  mariadb-galera:
    image: 'bitnami/mariadb-galera:latest'
    environment:
      - MARIADB_GALERA_CLUSTER_NAME=my_galera
      - MARIADB_GALERA_CLUSTER_ADDRESS=gcomm://galsera_mariadb-galera-bootstrap:4567,0.0.0.0:4567
      - MARIADB_GALERA_MARIABACKUP_USER=my_mariabackup_user
      - MARIADB_GALERA_MARIABACKUP_PASSWORD=my_mariabackup_password
      - MARIADB_ROOT_PASSWORD=my_root_password
      - MARIADB_REPLICATION_USER=my_replication_user
      - MARIADB_REPLICATION_PASSWORD=my_replication_password
    networks:
      - marianet
    deploy:
      replicas: 3
```

This adapts the [Setting up a multi-master cluster](https://github.com/bitnami/bitnami-docker-mariadb-galera#setting-up-a-multi-master-cluster) section of the Readme into Docker Swarm
