### ISSUE TITLE
If TLS is enabled then startup and readiness probes do not work

### ISSUE THREAD

**Issue by dejwsz** [bitnami/bitnami-docker-mariadb-galera#64]
**Description**

if TLS is enabled with custom cert secret or autogenerated one the startup and readiness probes are not working - they fail with error like:

```
probe failed: mysqladmin: unknown variable 'wsrep_provider_options=socket.ssl_cert=/bitnami/mariadb/certs/tls.crt;socket.ssl_key=/bitnami/mariadb/certs/tls.key;socket.ssl_ca=/bitnami/mariadb/certs/ca.crt'
```

Looks like "mysqladmin" command which is used there does not recognize "wsrep_provider_options" option in my.cnf
 like "mysql" used in livnessprobe which is working well.

**Steps to reproduce the issue:**

1. Start mariadb-galera cluster with TLS enabled
2. Just wait for warnings which are visible in k8s events
3. Event message explains the problem

**Describe the results you received:**

```
2m4s        Warning   Unhealthy                pod/wp-db-mariadb-galera-0                          Startup probe failed: mysqladmin: unknown variable 'wsrep_provider_options=socket.ssl_cert=/bitnami/mariadb/certs/tls.crt;socket.ssl_key=/bitnami/mariadb/certs/tls.key;socket.ssl_ca=/bitnami/mariadb/certs/ca.crt'

2m4s        Warning   Unhealthy                pod/wp-db-mariadb-galera-0                          Readiness probe failed: mysqladmin: unknown variable 'wsrep_provider_options=socket.ssl_cert=/bitnami/mariadb/certs/tls.crt;socket.ssl_key=/bitnami/mariadb/certs/tls.key;socket.ssl_ca=/bitnami/mariadb/certs/ca.crt'
```

**Describe the results you expected:**

All probes should work with TLS enabled.

**Comment by dejwsz** [comment]
"wsrep_provider_options" is just added at the end of the my.cnf config file - maybe this is wrong and some clients like mysqladmin cannot proceed with that option in this place

**Comment by dejwsz** [comment]
It starts working for after I set in my.cnf such values:

```
## SSL
## Use extraVolumes and extraVolumeMounts to mount /certs filesystem
ssl-cert=/bitnami/mariadb/certs/tls.crt
ssl-key=/bitnami/mariadb/certs/tls.key
ssl-ca=/bitnami/mariadb/certs/ca.crt
tls_version = TLSv1.2,TLSv1.3
require_secure_transport = 1
wsrep_provider_options = socket.ssl_cert=/bitnami/mariadb/certs/tls.crt
wsrep_provider_options = socket.ssl_key=/bitnami/mariadb/certs/tls.key
wsrep_provider_options = socket.ssl_ca=/bitnami/mariadb/certs/ca.crt
```

And in k8s deployment I added such ENV VARs:

```
            - name: MARIADB_ENABLE_TLS
              value: "yes"
            - name:  MARIADB_TLS_CERT_FILE
              value: /bitnami/mariadb/certs/tls.crt
            - name:  MARIADB_TLS_KEY_FILE
              value: /bitnami/mariadb/certs/tls.key
            - name:  MARIADB_TLS_CA_FILE
              value: /bitnami/mariadb/certs/ca.crt
```

and I mounts certificate via volume and used cert-manager to generate certificate with proper SANs:

```
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: db-cert
spec:
  isCA: false
  commonName: db-mariadb-galera
  secretName: db-cert
  dnsNames:
    - "*.db-mariadb-galera.##TARGET_NAMESPACE##.svc.cluster.local"
    - db-mariadb-galera.##TARGET_NAMESPACE##.svc.cluster.local
    - "*.db-mariadb-galera-headless.##TARGET_NAMESPACE##.svc.cluster.local"
    - db-mariadb-galera-headless.##TARGET_NAMESPACE##.svc.cluster.local
    - db-mariadb-galera
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
```
where ##TARGET_NAMESPACE## is just your target namespace the cluster operates in
