### ISSUE TITLE
gcomm:// is being used to bootstrap against documentation

### ISSUE THREAD

**Issue by nicolaerosia** [bitnami/bitnami-docker-mariadb-galera#76]
`get_galera_cluster_address_value` will set `cluster_address` to "gcomm://"`, however according to the documentation this is not correct:
```
Warning Never use an empty gcomm:// string with the wsrep_cluster_address option in the configuration file.
If a node restarts, it will cause the node not to rejoin the cluster.
Instead, it will initialize a new one-node cluster and cause a Split Brain.
To bootstrap a cluster, you should only pass the --wsrep-new-cluster string at the command-line–instead of using --wsrep-cluster-address="gcomm://".
For more information, see Starting the Cluster.
```
https://galeracluster.com/library/documentation/mysql-wsrep-options.html

**Comment by marcosbc** [comment]
Thanks for reporting this @nicolaerosia! It seems like this makes sense, but let's see what @rafariossaa thinks about this as well, since he is more familiar with the container and chart.

**Comment by rafariossaa** [comment]
Hi,
  Yes, we are taking a look to this issues. We will come back as soon as we have news.

**Comment by nicolaerosia** [comment]
I ended up reporting this because the helm chart that uses this image does not work in IPv6 only environments
I will try to provide a reproducer, https://github.com/bitnami/charts/issues/5842#issuecomment-1020852580

**Comment by rafariossaa** [comment]
Hi,
  Thanks for spotting this out.

**Comment by ioachim-hub** [comment]
# This is a reproducer
*kind.yaml*
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
  - role: control-plane
  - role: worker
    image: docker.io/kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
  - role: worker
    image: docker.io/kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
networking:
  ipFamily: ipv6
  apiServerAddress: "::"
  apiServerPort: 6443
```

helmfile.yaml
```
# yaml-language-server: $schema=https://json.schemastore.org/helmfile.json

helmDefaults:
  timeout: 600
  skipDeps: true
  historyMax: 2

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

missingFileHandler: Error

releases:
  # chart: https://github.com/bitnami/charts/tree/master/bitnami/mariadb-galera
  # history: https://github.com/bitnami/charts/commits/master/bitnami/mariadb-galera
  # https://artifacthub.io/packages/helm/bitnami/mariadb-galera/6.2.2
  # https://charts.bitnami.com/bitnami/mariadb-galera-6.2.2.tgz
  - name: mariadb-galera
    chart: bitnami/mariadb-galera
    namespace: default
    version: 6.2.2
    values:
      - rootUser:
          user: root
          password: "98cNUsR3gEyfYMrW"
          forcePassword: true
      - podAntiAffinityPreset: hard
      - replicaCount: 2
      - livenessProbe:
          enabled: true
          periodSeconds: 60
          timeoutSeconds: 10
      - readinessProbe:
          enabled: true
          periodSeconds: 60
          timeoutSeconds: 10
      - galera:
          mariabackup:
            user: mariabackup
            password: "qHmBRW7UfcVv27OD"
            forcePassword: true
```
